### ISSUE TITLE
Support the OAuth2 secret type

### ISSUE THREAD

**Issue by cmin764** [Sema4AI/actions#6]
### Why & who

We need this to instruct S4D, then CR/ACE, that such a flow needs to be completed in order to retrieve an access token in the action. 

This affects the Action Developer when the secret type gets configured with the required scopes and the auth provider info. This also enables the AI Operator to deploy such action requiring this kind of auth. And finally it affects the Knowledge Worker as well as it gives the ability to have a way to observe that such integration is required to be installed first before using the AI Actions.

### Feature or enhancement

Similar to `Secret` (that may be refactored into `SecretText`) we'd need a `SecretOAuth` new one which takes a list of scopes and the necessary auth provider info (auth & token URLs) so they can be collected by the auth manager in order to form the complete auth url (including the redirect URI) which triggers the flow (client install).

For the start, we may let the auth manager (S4D, CR) decide the auth & token URLs itself (harcoded) based on the specified provider in the OAuth2 secret type, so the Action Developer won't need to specify these in their actions. (potential limitation with custom Auth Provider servers or tenants requiring a mandatory tenant ID in the URLs -- see case explained below -> which gets solved by being configured straight in S4D, CR)

### Solution & alternative

- A new secret type called `SecretOAuth`
- `GoogleOAuth = SecretOAuth["google", ["read", "write"]]` -> would incapsulate the provider and the required scopes
- `def google_action(token: GoogleOAuth)` -> would instruct the auth manager that it needs the flow done
- In the function body we get the token with `token.access_token` -> offers the bearer access token which enables access into the API

The client credentials setup and token refreshing parts are handled by the auth manager (S4D, CR/ACE), never by the Action Package. The AI Actions would know just about the access token only and it should be ensured that this is valid.

### Notes

- On the auth manager side, operating with Public Apps (service approved clients) won't require the use of a `client_secret`. (`client_id` should be enough, but then it requires [PKCE](https://auth0.com/docs/get-started/authentication-and-authorization-flow/authorization-code-flow-with-pkce) layer in place)
- A follow-up requirement would be that we'll need [native DX support](https://linear.app/robocorp/issue/DEV-599/native-dx-during-action-development-with-oauth2) for the Action Developer to complete the flow straight from the Action Server.
- Here's diagram expressing the Authorization Code [grant type](https://miro.com/app/board/uXjVNmRRNk0=/?moveToWidget=3458764586514031099&cot=14) required to allow an app to act on user's behalf.
- The Office365 Exchange example where a custom tenant may also be required to craft the auth URL:
   1. Tenant [example](https://github.com/robocorp/example-oauth-email/blob/master/devdata/work-items-in/microsoft/work-items.json#L5)
   2. [Importing](https://github.com/robocorp/example-oauth-email/blob/master/tasks.robot#L40-L41) the legacy library with a custom tenant
   3. How tenant ID is [captured](https://github.com/robocorp/rpaframework/blob/master/packages/main/src/RPA/Email/Exchange.py#L298)
   4. Then [passed and formatted](https://github.com/robocorp/rpaframework/blob/master/packages/main/src/RPA/Email/common.py#L49-L52) in the auth & token URLs

[Linear](https://linear.app/robocorp/issue/DEV-655/support-the-oauth2-secret-type-in-the-action-server)

**Comment by kariharju** [comment]
For DX, in the examples we use to plot this let's use some actual scope strings as these can be "whatever", nasty, long and convoluted. Google and Slack as examples:
* https://developers.google.com/identity/protocols/oauth2/scopes
* https://api.slack.com/scopes

**Comment by cmin764** [comment]
@fabioz related to this Slack [thread](https://sema4ai.slack.com/archives/C070WBJRCT1/p1715678865511249?thread_ts=1715672257.422739&cid=C070WBJRCT1), please add here a metadata example so we won't keep S4D dev until this gets out.

**Comment by fabioz** [comment]
Proposed metadata:

```
{
    "metadata": {
        "name": "Package Name",
        "description": "Package description.",
        "secrets": {
            "/api/actions/package-name/action-name/run": {
                "action": "action_name",
                "actionPackage": "Package Name",
                "secrets": {
                    "api_key": {
                        "type": "Secret"
                    },
                    "access_token": {
                        "type": "OAuth2Secret",
                        "provider": "google",
                        "scopes": ["http://foo.bar/read", "http://bar.foo/write"]
                    }
                }
            }
        }
    },
```

**Comment by fabioz** [comment]
Proposed sema4ai-code structure:

```
from typing import Generic, Literal, TypeVar

from robocorp.actions import action

# Definition (internal to sema4ai-actions)
ProviderT = TypeVar("ProviderT", bound=str)  # Restrict Provider to string
ScopesT = TypeVar("ScopesT", bound=list)

JSONValue = dict[str, "JSONValue"] | list["JSONValue"] | str | int | float | bool | None


class OAuth2Secret(Generic[ProviderT, ScopesT]):
    def __init__(
        self,
        provider: ProviderT,
        scopes: ScopesT,
        token: str,
        metadata: JSONValue = None,
    ):
        self._provider = provider
        self._scopes = scopes
        self._token = token
        self._metadata = metadata

    @property
    def provider(self) -> str:
        return self._provider

    @property
    def scopes(self) -> ScopesT:
        return self._scopes

    @property
    def token(self) -> str:
        return self._token

    @property
    def metadata(self) -> JSONValue:
        return self._metadata


# Code which the user needs to write
@action
def send_message(
    message: str,
    access_token: OAuth2Secret[
        Literal["google"],
        list[
            Literal[
                "https://www.googleapis.com/auth/spreadsheets",
                "https://www.googleapis.com/auth/drive.file",
            ]
        ],
    ],
) -> str:
    # Actual instance (received in the arguments) is created from the
    # action server with something as:
    access_token = OAuth2Secret(
        "google",
        [
            "https://www.googleapis.com/auth/spreadsheets",
            "https://www.googleapis.com/auth/drive.file",
        ],
        "auth-token",
    )
    print(access_token.provider)
    print(access_token.scopes)
    print(access_token.token)
    print(access_token.metadata)
    return ""
```

**Comment by fabioz** [comment]
Fixed in https://github.com/Sema4AI/actions/commit/a3a2d7b675412f39492544b2720c0cf6229e7ad2
